###########################################
############ CREATE API ###################

### CUSTOMER CREATE API
POST http://localhost:9200/customers/_create/contoh
Content-Type: application/json

{
    "name": "Abang Kuy",
    "register_at": "2024-10-23 17:00:23"
}


### GET Customers mapping
GET http://localhost:9200/customers/_mapping

### Create products 1
POST http://localhost:9200/products/_create/1
Content-Type: application/json

{
    "name": "Indomie Ayam Bawang",
    "price": "2000"
}

### Create products 1
POST http://localhost:9200/products/_create/2
Content-Type: application/json

{
    "name": "Mie Sedap Soto",
    "price": 3000
}

### Products Mapping
GET http://localhost:9200/products/_mapping

### Orders Mapping
GET http://localhost:9200/orders/_mapping

### Create orders 1
POST http://localhost:9200/orders/_create/1
Content-Type: application/json

{
    "order_date": "2024-10-12 00:00:00",
    "customer_id": "contoh",
    "total": 8000,
    "items":[
        {
            "product_id": "1",
            "price": "2000",
            "quantity": "2"
        },
        {
            "product_id": "2",
            "price": "3000",
            "quantity": "2"
        }
    ]
}

###########################################
############ GET API ###################

### CUSTOMER GET API
GET http://localhost:9200/customers/_doc/contoh

### CUSTOMER GET - SOURCE API
GET http://localhost:9200/customers/_source/contoh

### CUSTOMER GET API NOT FOUND
GET http://localhost:9200/customers/_doc/slah


### CUSTOMER GET - CHECK IF EXIST
HEAD http://localhost:9200/customers/_doc/contoh

### CUSTOMER GET - CHECK IF EXIST (NOT EXIST)
HEAD http://localhost:9200/customers/_doc/salah

###########################################
############ MULTI GET API ###################

### get product 1 and 2

GET http://localhost:9200/products/_mget
Content-Type: application/json

{
    "ids":[
        "1","2"
    ]
}

### get order 1 and customer contoh

GET http://localhost:9200/_mget
Content-Type: application/json

{
    "docs": [
        {
            "_id": "1",
            "_index":"orders"
        },
        {
            "_id":"contoh",
            "_index": "customers"
        }
    ]
    
}

###########################################
############ SEARCH API ###################

### Search all product
POST http://localhost:9200/products/_search


### search all product page 1
POST http://localhost:9200/products/_search?size=1&from=0

### search all product page 2
POST http://localhost:9200/products/_search?size=1&from=1

### search all product sort by price
POST http://localhost:9200/products/_search?sort=price:asc

### search all product sort by price
POST http://localhost:9200/products/_search?sort=name:desc


###########################################
############ INDEX API ###################

### create product 3
POST http://localhost:9200/products/_doc/3
Content-Type: application/json

{
  "name" : "Pop Mie Rasa Bakso",
  "price": 2500
}

### create product 4
POST http://localhost:9200/products/_doc/4
Content-Type: application/json

{
  "name" : "Samsung Galaxy S9+",
  "price": 10000000
}

### create product 5
POST http://localhost:9200/products/_doc/5
Content-Type: application/json

{
  "name" : "Acer Predator XXI",
  "price": 25000000
}

### get product 5
GET http://localhost:9200/products/_doc/5

### search all products
POST http://localhost:9200/products/_search

###########################################
############ UPDATE API ###################

### update price for product 5
POST http://localhost:9200/products/_update/5
Content-Type: application/json

{
  "doc" : {
    "price": 30000000
  }
}

###########################################
############ DELETE API ###################

### insert customer spammer
POST http://localhost:9200/customers/_create/spammer
Content-Type: application/json

{
  "name" : "spammer",
  "register_at" : "2023-10-10 00:00:00"
}

### delete customer spammer
DELETE http://localhost:9200/customers/_doc/spammer

###########################################
############ BULK API ###################


### bulk api
POST http://localhost:9200/_bulk
Content-Type: application/json

# {"create" :  {"_index" :  "customers", "_id":  "joko"}}
# {"name" :  "Joko Morro", "register_at": "2023-10-10 00:00:00"}
# {"index" :  {"_index" :  "customers", "_id":  "budi"}}
# {"name" :  "Budi Nugraha", "register_at": "2023-10-10 00:00:00"}
# {"update" :  {"_index" :  "products", "_id":  "1"}}
# {"doc" :  {"price" :  2500}}
# {"create" :  {"_index" :  "customers", "_id":  "spammer"}}
# {"name" :  "Spammer", "register_at": "2023-10-10 00:00:00"}
# {"delete" :  {"_index" :  "customers", "_id":  "spammer"}}
< bulk.json


###########################################
############ ALIAS ###################

### single, customer alias
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "add": {
                "index": "customers",
                "alias": "customer"
            }
        }
    ]
}

### banyak, customer, order alias
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "add": {
                "index": "customers",
                "alias": "customer"
            }
            
        },
        {
            "add": {
                "alias":"order",
                "index": "orders"
            }
        }
    ]
}

### get alias
GET http://localhost:9200/_aliases

### search customer menggunakan alias
GET http://localhost:9200/customer/_search

###########################################
############ REINDEX ###################

### create new index orders
PUT http://localhost:9200/orders_v2

### mapping
PUT http://localhost:9200/orders_v2/_mapping
Content-Type: application/json

{
    "numeric_detection": true,
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]

}

### reindex orders data
POST http://localhost:9200/_reindex
Content-Type: application/json

{
    "source": {
        "index": "orders"
    },
    "dest": {
        "index": "orders_v2"
    }
}

### get order data from orders_v2
GET http://localhost:9200/orders_v2/_search

### switch alias order from orders to orders_v2
### remove alias from orders
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "remove": {
                "index": "orders",
                "alias": "order"
            }
        }
    ]
}

### add alias to orders_v2
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "add": {
                "index": "orders_v2",
                "alias": "order"
            }
        }
    ]
}

### lebih simple langsung disatuin aja
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "remove": {
                "index": "orders",
                "alias": "order"
            }
        },
        {
            "add": {
                "index": "orders_v2",
                "alias": "order"
            }
        }
    ]
}

### check alias
GET http://localhost:9200/_aliases

### search order alias
GET http://localhost:9200/order/_search


###########################################
############ SOURCE include ###################

## select total, customer_id, items.product_d from order
GET http://localhost:9200/order/_search?_source_includes=total,customer_id,items.product_id

### select *, exclude price from products
GET http://localhost:9200/products/_search?_source_excludes=price

### select total, customer_id from order where _id = 1
GET http://localhost:9200/order/_doc/1?_source_includes=total,customer_id