### Create index customer_v2
PUT http://localhost:9200/customers_v2

### Update mapping customers_v2
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
    "numeric_detection": true,
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ],
    "properties": {
        "username": {
            "type": "keyword"
        },
        "first_name": {
            "type": "text"
        },
        "last_name": {
            "type": "text"
        },
        "email": {
            "type": "keyword"
        },
        "gender": {
            "type": "keyword"
        },
        "birth_date": {
            "type": "date",
            "format": "yyyy-MM-dd"
        }
    }
}

### get mapping customers_v2
GET http://localhost:9200/customers_v2/_mapping

### switch alias customer from customers to customers_v2
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "remove":{
                "alias": "customer",
                "index": "customers"
            }
        },
        {
            "add":{
                "alias": "customer",
                "index": "customers_v2"
            }
        }
    ]
}


### get aliases
GET http://localhost:9200/_aliases

### search customer
GET http://localhost:9200/customer/_search

### bulk insert customer
POST http://localhost:9200/_bulk
Content-Type: application/json

< customers.json

### update customers_v2 mapping
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
  "properties" : {
    "address" : {
      "properties" : {
        "street" : {
          "type" : "text"
        },
        "city" : {
          "type" : "text"
        },
        "province" : {
          "type" : "text"
        },
        "country" : {
          "type" : "text"
        },
        "zip_code" : {
          "type" : "keyword"
        }
      }
    }
  }
}

### bulk insert customer with addresses
POST http://localhost:9200/_bulk
Content-Type: application/json

< customers_with_addresses.json


### update customers_v2 mapping
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
  "properties": {
    "hobbies": {
      "type": "text"
    },
    "banks": {
      "properties": {
        "name": {
          "type": "text"
        },
        "account_number": {
          "type": "keyword"
        }
      }
    }
  }
}

### get customers_v2 mapping
GET http://localhost:9200/customers_v2/_mapping

### bulk index customers_v2
POST http://localhost:9200/_bulk
Content-Type: application/json

< customer-with-banks-and-hobbies.json

### search customer
POST http://localhost:9200/customer/_search


### search customer using match all
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
    "query": {
        "match_all": {}
    } 
    
}

### search customer using match all with sort 
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
    "query": {
        "match_all": {}
    },
    "size": 5,
    "from": 0,
    "sort": [
        {
            "username": {
                "order": "desc"
            }
        }
    ] 
    
}

### search customer where gender = 'Female'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "term" : {
      "gender" : "Female"
    }
  },
  "size" : 5,
  "from" : 0,
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}

### search customer where banks.name = 'BCA'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "term" : {
      "banks.name" : "BCA"
    }
  },
  "size" : 5,
  "from" : 0,
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}

### search customer where banks.name = 'BCA'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "match" : {
      "banks.name" : "BCA"
    }
  },
  "size" : 5,
  "from" : 0,
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}

### search customer where banks.name = 'BCA DIGITAL'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "match" : {
      "banks.name" : {
        "query" : "BCA DIGITAL",
        "operator" : "AND"
      }
    }
  },
  "size" : 5,
  "from" : 0,
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}

### search customer where username IN ('username1', 'username2', 'username3')
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "username": [
        "username1",
        "username2",
        "username3"
      ]
    }
  }
}

### search customer where banks.name IN ('BCA', 'BTN', 'BNI')
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "banks.name": [
        "bca",
        "btn",
        "bni"
      ]
    }
  }
}


### search customer where hobbies = 'gaming' AND banks.name = 'bca'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "term": {
            "banks.name": "bca"
          }
        }
      ]
    }
  }
}

### search customer where hobbies = 'gaming' AND banks.name = 'bca digital'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "match": {
            "banks.name": {
                "query": "bca digital",
                "operator": "AND"
            }
          }
        }
      ]
    }
  }
}

### search customer where hobbies = 'gaming' AND banks.name = 'bca'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "match": {
            "banks.name": {
              "query" : "bca digital",
              "operator" : "AND"
            }
          }
        }
      ]
    }
  },
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}

### search customer where hobbies != 'gaming' AND banks.name != 'bca digital'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must_not": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "match": {
            "banks.name": {
              "query": "bca digital"
            }
          }
        }
      ]
    }
  }
}


### search customer where hobbies = 'GAMING' AND (banks.name = 'bca' OR 'banks.name = 'bni)
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must" : [
        {
          "term" : {
            "hobbies" : "gaming"
          }
        }
      ],
      "should": [
        {
          "term": {
            "banks.name": "bca"
          }
        },
        {
          "term": {
            "banks.name": "bni"
          }
        }
      ],
      "minimum_should_match" : 1
    }
  }
}

### explain score for customer username126
POST http://localhost:9200/customer/_explain/username126
Content-Type: application/json

{
  "query": {
    "bool": {
      "must" : [
        {
          "term" : {
            "hobbies" : {
              "value" : "gaming",
              "boost" : 0
            }
          }
        }
      ],
      "should": [
        {
          "term": {
            "banks.name": "bca"
          }
        },
        {
          "term": {
            "banks.name": "bni"
          }
        }
      ],
      "minimum_should_match" : 1
    }
  }
}

### search customer where (banks.name = 'bca' OR 'banks.name = 'bni)
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "banks.name": {
              "value" : "bca",
              "boost" : 0
            }
          }
        },
        {
          "term": {
            "banks.name": {
              "value" : "bni",
              "boost" : 2
            }
          }
        }
      ]
    }
  }
}

### update customer mapping
PUT http://localhost:9200/customer/_mapping
Content-Type: application/json

{
  "properties" : {
    "labels" : {
      "type": "flattened"
    }
  }
}

### get customer mapping
GET http://localhost:9200/customer/_mapping

### update customer username1
POST http://localhost:9200/customer/_update/username1
Content-Type: application/json

{
  "doc" : {
    "labels" : {
      "priority" : "vip",
      "discount" : "10% discount",
      "complaint": "always complaint"
    }
  }
}

### get customer username1
GET http://localhost:9200/customer/_doc/username1

### update customer username2
POST http://localhost:9200/customer/_update/username2
Content-Type: application/json

{
  "doc" : {
    "labels" : {
      "priority" : "regular",
      "verified" : "unverified",
      "buy" : "never buy"
    }
  }
}

### get customer username2
GET http://localhost:9200/customer/_doc/username2

### search vip customer
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "term" : {
      "labels": "regular"
    }
  }
}

### search vip and regular customer
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "bool" : {
      "should" : [
        {
          "term" : {
            "labels.priority" : "vip"
          }
        },
        {
          "term" : {
            "labels.priority" : "regular"
          }
        }
      ]
    }
  }
}